SUPABASE_URL = "https://njtnsqtrfypqdgqrkplf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qdG5zcXRyZnlwcWRncXJrcGxmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTM5ODE4NiwiZXhwIjoyMTAwOTc0MTg2fQ.eNaWc_mwDAmIVXbQD1V63zLNQ7ZW9h1iQxPLqbgo8iM"
GOOGLE_API_KEY = "AIzaSyAmls33fhOUBRDc5dQfI_-AAJp12QHhGLo"